
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: expensio_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: expensio_test
  pool: 5

production:
  <<: *default
  database: expensio_production
